name = "MultithreadingBenchmarks"
uuid = "95dfcc4a-c450-11e9-2039-9ba35aa0ffba"
authors = ["Nathan Daly"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
